<?php
require('functions.php');
echo "<br>------------------Task1--------------- <br>";
echo task1(array ('My', 'name', 'is', 'Zeus!'), true);
echo "<br>------------------Task2--------------- <br>";
echo task2(array(1, 2, 3, 4,5), '+');
echo "<br>------------------Task3--------------- <br>";
echo task3('/', 625, 25, 5);
echo "<br>------------------Task4--------------- <br>";
echo task4(8, 8);
echo "<br>------------------Task5--------------- <br>";
echo task5('eng isi gne');
echo "<br>------------------Task6--------------- <br>";
echo task6();
echo "<br>------------------Task7--------------- <br>";
echo task7();
echo "<br>------------------Task8--------------- <br>";
echo task8('RX packets:101010 errors:0 dropped:0  overruns:0 frame:0. :)');
echo "<br>------------------Task9--------------- <br>";
echo task9('text.txt');
echo "<br>------------------Task10-------------- <br>";
echo task10('anothertest.txt ');